### ISSUE TITLE
MacRuby not found

### ISSUE THREAD

**Issue by Jones-S** [kourge/plumage#1]
Hi

I am desperately trying to convert an .itermcolors file with a color scheme to a color profile for my terminal which I use with zsh. I came across your script which I understood is able to convert a file.itermcolors to a file which I can import into my terminal profiles.
I downloaded your script but unfortunately I get this error:
`plumage.rb:220:in `relaunch_in_macruby!': Could not find MacRuby (RuntimeError)
    from plumage.rb:227:in `<main>'`

Although I have Mac OS X Capitan and Xcode 7 inclusive command line tools installed.

I tried to run your code either with the command
`$ ruby plumage.rb`
or also with the full command to convert the itermcolors to the terminal colors:
`$ ruby plumage.rb -o terminalapp /Users/myName/Desktop/paraiso.itermcolors ~/Desktop/Colors.terminal`

Both will give me the «Could not find MacRuby» message.
Any idea how to solve this problem?
Or any other idea how to get a nice looking zsh-terminal without iterm but using an itermcolors-file?

Thanks very much in advance.

Cheers

**Comment by kourge** [comment]
Since OS X Mountain Lion (10.8), [MacRuby](https://en.wikipedia.org/wiki/MacRuby) hasn't had a new release, nor has it been bundled with OS X.

So there are two problems with plumage right now:
- It relies on MacRuby to read / write plist files
- Its mapping of colors between Terminal.app and iTerm2 may no longer be accurate

Solving the first one is not too difficult; I can just rewrite this in something else (e.g. Swift). If the second one becomes an actual problem, it'll take me some time to figure out any changes in format.

**Comment by Jones-S** [comment]
Hey thanks for the answer. I see the problem with MacRuby. :)
Anyway I found the color-scheme I wanted already in the .terminal format. So it's not that important anymore right now. But feel free to update the script. Maybe someone else needs it one day :smile: 
thanks anyway

**Comment by brunolemos** [comment]
Works after installing MacRuby form here http://macruby.jp/files/nightlies/
